//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyIE.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MYIE                        102
#define IDS_MYIENSHANDLE_DESC           103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MyIENSHandle                105
#define IDD_PROPPAGE_GENERAL            106
#define IDD_URL_FILTER                  107
#define IDR_MAINFRAME                   128
#define IDR_MyIEYPE                     129
#define IDR_MFCIETYPE                   129
#define IDS_SHLWAPI_FAIL                130
#define IDR_MFCAVI                      131
#define IDS_UNTITLED                    131
#define IDR_FONT_POPUP                  132
#define IDS_CLOSE_ALL_CONF              132
#define IDR_FAVORITES_POPUP             133
#define IDS_POPUP_CONF                  133
#define IDS_FAIL_ADDR_BOOK              134
#define IDB_BITMAP1                     135
#define IDS_FAIL_EMAIL                  135
#define IDS_CLEAN_ALL                   136
#define IDS_DEFAULT_WEB_PROXY           137
#define IDS_NO_PROXY                    138
#define IDS_PROXY_FAIL                  139
#define IDR_RTAB                        140
#define IDS_CHANGE_POS                  140
#define IDD_POPUPLIST                   141
#define IDS_UTIL_FAIL                   141
#define IDD_SET_PROXY                   142
#define IDS_TITLE_HIS                   142
#define IDS_TITLE_SEARCH                143
#define IDR_ENCODING                    144
#define IDS_WEEKS_AGO                   144
#define IDD_EXTERN_UTIL                 145
#define IDS_SUNDAY                      145
#define IDD_INPUT_UTIL                  146
#define IDS_MONDAY                      146
#define IDS_TUESDAY                     147
#define IDB_BITMAP2                     148
#define IDS_WEDNESDAY                   148
#define IDS_THURSDAY                    149
#define IDS_FRIDAY                      150
#define IDR_SEARCH                      150
#define IDS_SATURDAY                    151
#define IDS_TODAY                       152
#define IDS_LAST_WEEK                   153
#define IDS_USE_PROXY                   154
#define IDS_LINKS                       155
#define IDS_STARTUP                     156
#define IDS_UNSET_START_FOLDER          156
#define IDB_BITMAP3                     157
#define IDS_SPACES                      157
#define IDB_BITMAP4                     158
#define IDS_WARNING                     158
#define IDR_RFAV_URL                    159
#define IDS_VTILE                       159
#define IDR_RFAV_FOLDER                 160
#define IDS_HTILE                       160
#define IDB_BITMAP5                     161
#define IDS_WEB_PROXY                   161
#define IDB_BITMAP6                     162
#define IDS_PROXY                       162
#define IDR_SPEED                       163
#define IDS_ENCODE                      163
#define IDS_UNSET_MOST_FAV              164
#define IDR_F2F12                       164
#define IDS_NOT_URL                     165
#define IDD_SET_KEY                     165
#define IDS_UNSET_MOST_FOLDER           166
#define IDS_CONFIRM_DEL                 167
#define IDD_SET_ALIAS                   168
#define IDS_PROXY_ADDED                 168
#define IDD_INPUT_ALIAS                 169
#define IDS_RESUME                      169
#define IDD_CUSTOMIZE                   170
#define IDS_IMPORT_PROXY                170
#define IDD_MYIEOPTION                  171
#define IDS_COMFIRM_CATE_DEL            171
#define IDD_STICKNAME                   172
#define IDS_CANT_MOVE_PROXY             172
#define IDD_FILEOPEN                    173
#define IDS_DEFAULT_WEBP_NAME           173
#define IDD_PASSWORD                    174
#define IDS_INVALIDSEARCHNAME           174
#define IDB_BITMAP7                     175
#define IDS_NEEDKEYSTRING               175
#define IDB_BITMAP8                     176
#define IDS_SAVEDFORM                   176
#define IDB_BITMAP9                     177
#define IDS_MYIESHEET                   177
#define IDI_TRAY                        178
#define IDS_DEFAULTPOS                  178
#define IDS_SAVEIMAGEFAIL               179
#define IDI_ICON1                       180
#define IDS_FILTERSHEET                 180
#define IDD_ORG_GROUP                   181
#define IDD_GROUP_URL                   182
#define IDD_PROXY                       183
#define IDR_HIS_FOLDER                  185
#define IDR_HIS_URL                     186
#define IDD_SETREFRESH                  188
#define IDB_COLDSM                      189
#define IDB_HOTSM                       190
#define IDD_SELPROXYCAT                 191
#define IDB_BITMAP10                    193
#define IDB_BITMAP11                    194
#define IDD_QUICKSEARCH                 195
#define IDD_INPUT_QUICKSEARCH           196
#define IDI_SECURE                      198
#define IDB_BITMAP12                    199
#define IDB_BITMAP13                    200
#define IDD_COLLECTOR                   201
#define IDD_DOWNLOAD                    202
#define IDD_LINKLIST                    203
#define IDC_POINTER_DRAG                204
#define IDD_PROPPAGE_WINDOW             205
#define IDD_PROPPAGE_TAB                206
#define IDD_PROPPAGE_STARTUP            207
#define IDD_PROPPAGE_DOWNLOAD           208
#define IDD_PROPPAGE_OTHERS             209
#define IDD_ADDURLHERE                  211
#define IDD_PROPPAGE_SAVE               213
#define IDB_COLDTOOLBAR                 261
#define IDB_HOTTOOLBAR                  262
#define IDS_WEB_TUTORIAL                736
#define IDS_ONLINE_SUPPORT              737
#define IDS_FREE_STUFF                  738
#define IDS_GET_FASTER_INTERNET_ACCESS  741
#define IDS_FREQUENTLY_ASKED_QUESTIONS  742
#define IDS_INTERNET_START_PAGE         743
#define IDS_SEND_FEEDBACK               744
#define IDS_BEST_OF_THE_WEB             745
#define IDS_SEARCH_THE_WEB              746
#define IDS_MICROSOFT_HOME_PAGE         747
#define IDS_BACK                        748
#define IDS_FORWARD                     749
#define IDS_STOP                        750
#define IDS_REFRESH                     751
#define IDS_HOME                        752
#define IDS_SEARCH                      753
#define IDS_FAVORITES                   754
#define IDS_PRINT                       755
#define IDS_FONT                        756
#define IDS_ADDRESS                     757
#define ID_KEYWORD                      758
#define IDS_MY_COMPUTER                 759
#define IDS_SET_DEFAULT                 760
#define IDS_TITLE_FAVORITE              761
#define IDS_FAV_ADD                     762
#define IDS_FAV_ORG                     763
#define IDS_CHANNEL                     764
#define IDS_CHANNEL_E                   765
#define IDS_OPEN_ALL_FAV                766
#define IDS_NEW_WINDOW                  767
#define IDS_IMAGE                       768
#define IDS_SP_INVALID                  769
#define IDS_SP_SLOWER                   770
#define IDS_SP_SLOW                     771
#define IDS_SP_NOR                      772
#define IDS_SP_FAST                     773
#define IDS_SP_FASTER                   774
#define IDS_OPEN_ALL_MOSTFAV            775
#define IDS_FAV_MOST                    776
#define IDS_ALIAS                       777
#define IDS_SEPARATOR                   778
#define IDS_CANT_DO                     779
#define IDS_EX_TOOL                     780
#define IDS_TITLE_SHELL                 781
#define IDS_TITLE_RESOURCE              782
#define IDS_ROWSE_MODE                  783
#define IDS_AUTO_SCROLL                 784
#define IDS_SAVE_AS                     785
#define IDS_AUTOFILTER                  786
#define IDS_ADDFAV                      787
#define IDS_FZQK                        788
#define IDS_PAGE_SAVED                  789
#define IDC_ENABLE_POPUP                1000
#define IDC_INSERT                      1002
#define IDC_EDIT                        1003
#define IDC_DELETE                      1004
#define IDC_USER_PROXY                  1006
#define IDC_PROXY_LIST                  1007
#define IDC_USE_WEB_PROXY               1008
#define IDC_WEB_PRO_LIST                1009
#define IDC_EXTERN_UTIL                 1012
#define IDC_ADD_UTIL                    1013
#define IDC_MOD_UTIL                    1014
#define IDC_DEL_UTIL                    1015
#define IDC_NAME                        1016
#define IDC_COMMAND                     1017
#define IDC_BROWSER_FILE                1018
#define IDC_EDIT1                       1019
#define IDC_PROXY_NEW                   1028
#define IDC_PROXY_DEL                   1029
#define IDC_WEB_PROXY_NEW               1030
#define IDC_WEB_PROXY_DEL               1031
#define IDC_SPIN1                       1032
#define IDC_SPIN2                       1033
#define IDC_LIST1                       1040
#define IDC_KEYLIST                     1041
#define IDC_UPDATE                      1043
#define IDC_DEL                         1046
#define IDC_NEW                         1047
#define IDC_URL                         1048
#define IDC_ALIAS                       1049
#define IDC_CURBTN                      1050
#define IDC_ADD                         1051
#define IDC_REMOVE                      1052
#define IDC_MOVEUP                      1054
#define IDC_MOVWDOWN                    1055
#define IDC_AVABTN                      1056
#define IDC_DLIMG                       1057
#define IDC_DLSOUND                     1058
#define IDC_DLVIDEO                     1059
#define IDC_DLJS                        1060
#define IDC_DLAPPLET                    1061
#define IDC_DLACTIVEX                   1062
#define IDC_SKINPATH                    1063
#define IDC_MAXCHARS                    1064
#define IDC_MAXWIDTH                    1065
#define IDC_COMFIRMEXIT                 1066
#define IDC_SAVEPATH                    1067
#define IDC_CE2                         1068
#define IDC_CSE1                        1069
#define IDC_CSE2                        1070
#define IDC_SE1                         1071
#define IDC_SE2                         1072
#define IDC_CE1                         1073
#define IDC_MAXMENU                     1074
#define IDC_SINGLEMENU                  1075
#define IDC_SYSTRAY                     1076
#define IDC_MAXWIN                      1077
#define IDC_STICKNAME                   1078
#define IDC_KEEPSILENT                  1079
#define IDC_MINWIDTH                    1080
#define IDC_BROWSE                      1081
#define IDC_ADDRESS                     1082
#define IDC_REM_PSW                     1085
#define IDC_PASSWORD                    1086
#define IDC_STARTUP                     1087
#define IDC_INTERVAL                    1088
#define IDC_CONFIRMCLOSEALL             1089
#define IDC_ONLYONE                     1090
#define IDC_BYPASS                      1091
#define IDC_NEW_GROUP                   1094
#define IDC_DEL_GROUP                   1095
#define IDC_URL_LIST                    1101
#define IDC_GROUP_LIST                  1102
#define IDC_BLANKWIN                    1104
#define IDC_HOME                        1105
#define IDC_CURWIN                      1106
#define IDC_BLANKWIN2                   1107
#define IDC_ALLOW_DBC                   1108
#define IDC_HOME2                       1108
#define IDC_GROUP_PATH                  1109
#define IDC_CURWIN2                     1109
#define IDC_MODIFYPROXY                 1110
#define IDC_WEBPROXY_MODIFY             1111
#define IDC_PROXY                       1112
#define IDC_SPEED                       1113
#define IDC_COLOR_ICON                  1114
#define IDC_TEXT_OPT                    1115
#define IDC_DISPLAY_OPENALL             1116
#define IDC_REFINTERVAL                 1117
#define IDC_ICON_OPT                    1118
#define IDC_PROXYCATS                   1119
#define IDC_CLEAR                       1120
#define IDC_CATES                       1121
#define IDC_NEWCATE                     1122
#define IDC_DELCATE                     1124
#define IDC_CLOSEUTIL                   1125
#define IDC_AUTO_FILTER                 1126
#define IDC_FILTER_DUP                  1127
#define IDC_SEACHLIST                   1129
#define IDC_SEARCHENGINE                1133
#define IDC_RICHEDIT1                   1134
#define IDC_TXT                         1135
#define IDC_NO_TOOL                     1137
#define IDC_NETANTS                     1138
#define IDC_FLASHGET                    1139
#define IDC_FILEEXT                     1140
#define IDC_SELECTTOOLS                 1141
#define IDC_DISP_ANIICON                1142
#define IDC_COMPACTFAVBAR               1143
#define IDC_MULTILINE_TAB               1146
#define IDC_AUTOFIT_TAB                 1147
#define IDC_DISP_NEXT_TAB               1148
#define IDC_NEW_ADDRESS                 1149
#define IDC_FAV_LNK                     1150
#define IDC_HISTORY                     1151
#define IDC_LOCALFILE                   1152
#define IDC_LINKSINPAGE                 1153
#define IDC_ACTIVATE_NEWWIN             1154
#define IDC_DEFAULT_SEQ                 1155
#define IDC_NEXT_SEQ                    1156
#define IDC_PRE_SEQ                     1157
#define IDC_START_BLANK                 1158
#define IDC_START_HOME                  1159
#define IDC_START_LASTVISIT             1160
#define IDC_START_STARTFAV              1161
#define IDC_START_MOSTFAV               1162
#define IDC_START_STARTGROUP            1163
#define IDC_TAB_TOP                     1164
#define IDC_BOTTOM_TAB                  1165
#define IDC_LDBCLICK                    1166
#define IDC_MCLIK                       1167
#define IDC_PLAY_ANIMATION              1168
#define IDC_IMAGEPATH                   1169
#define IDC_FOLDER                      1171
#define IDC_ADDFAV                      1172
#define IDC_MOUSEGESTURE                1173
#define IDC_LOCKHOME                    1174
#define IDC_AUTOSAVE                    1175
#define IDC_CATEWITHSITE                1176
#define IDC_RCLIK                       1179
#define IDC_URL_FILTER                  1181
#define IDC_START_NONE                  1185
#define IDC_FLATBUTAB                   1186
#define IDC_ADDRS                       1188
#define IDC_DELETEALL                   1190
#define IDS_FILETYPES                   1201
#define ID_FILE_NEW_BLANK               32772
#define ID_FILE_NEW_CURRENTPAGE         32773
#define ID_FILE_CLOSE_2                 32774
#define ID_FILE_CLOSEALL                32775
#define ID_FILE_CLOSE_1                 32776
#define ID_FILE_SAVEAS                  32777
#define ID_VIEW_STOP                    32778
#define ID_VIEW_REFRESH                 32779
#define ID_FILE_WORKOFFLINE             32780
#define ID_VIEW_ADDRESSBAR              32781
#define ID_VIEW_FONTS_LARGEST           32782
#define ID_VIEW_FONTS_LARGE             32783
#define ID_VIEW_FONTS_MEDIUM            32784
#define ID_VIEW_FONTS_SMALL             32785
#define ID_VIEW_FONTS_SMALLEST          32786
#define ID_GO_BACK                      32787
#define ID_GO_FORWARD                   32788
#define ID_GO_START_PAGE                32789
#define ID_GO_SEARCH_THE_WEB            32790
#define ID_GO_BEST_OF_THE_WEB           32791
#define ID_VIEW_TASKBAR                 32792
#define ID_FAVORITES_DROPDOWN           32793
#define ID_VIEW_SOURCE                  32794
#define ID_FONT_DROPDOWN                32795
#define ID_TOOLS_INTERNETOPTIONS        32796
#define ID_HELP_WEB_TUTORIAL            32798
#define ID_FILE_SAVEHTML                32798
#define ID_ENCODE_DROPDOWN              32799
#define ID_BMODE_DROPDOWN               32800
#define ID_FAVORITES_ADDTOFAVORITES     32803
#define ID_FAVORITES_ORGNIZEFAVORITES   32804
#define ID_FAVORITES_IMPORTFAVORITES    32805
#define ID_FAVORITES_EXPORTFAVORITES    32806
#define ID_OPTIONS_MYIEOPTIONS          32807
#define ID_OPTIONS_LOADIMAGE            32808
#define ID_OPTIONS_LOADVIDEOS           32809
#define ID_OPTIONS_LOADSOUNDS           32810
#define ID_OPTIONS_LOADANIMATIONS       32811
#define ID_OPTIONS_ALLOWSCRIPTS         32812
#define ID_RTAB_LOCK                    32815
#define ID_RTAB_ADDTOPOPUPFILTER        32816
#define ID_BOGUS                        32817
#define ID_TOOLS_ADDTOPOPUPFILTER       32818
#define ID_TOOLS_EDITPOPUPFILTERLIST    32819
#define ID_TOOLS_EABLEPOPUPFILTER       32820
#define ID_TOOLS_EMAIL                  32821
#define ID_TOOLS_ADDR                   32822
#define ID_TOOLS_ALERT                  32823
#define ID_TOOLS_COOKIE                 32824
#define ID_TOOLS_HISTORY                32825
#define ID_TOOLS_CACHE                  32826
#define ID_TOOLS_ALL                    32827
#define ID_OPTIONS_USE_PROXY            32828
#define ID_OPTIONS_SET_PROXY            32829
#define ID_OPTIONS_USE_WEBP             32830
#define ID_OPTIONS_ALLOWJAVAAPPLET      32832
#define ID_OPTIONS_ALLOWACTIVEX         32833
#define ID_VIEW_ENCODING_WESTERNEUROPEAN 32836
#define ID_VIEW_ENCODING_CHINESESIMPLIFIED 32837
#define ID_VIEW_ENCODING_CHINESETRADITIONAL 32838
#define ID_VIEW_ENCODING_JANESE         32839
#define ID_OPTION_TOP_TAB               32840
#define ID_OPTION_BOT_TAB               32841
#define ID_VIEW_HIS                     32842
#define ID_TOOLS_EXTERNALUTILITIES_UTILITYMANAGER 32843
#define ID_VIEW_EXPLOREBAR_SEARCH       32844
#define ID_VIEW_FULLSCREEN              32845
#define ID_OPTIONS_SETASDEFAULTBROWSER  32846
#define ID_FAV_POPUP                    32847
#define ID_ADDR_DROP                    32848
#define ID_ADDR_FOCUS                   32849
#define ID_FILE_NEW_S                   32852
#define ID_HELP_HELP                    32853
#define ID_OPTIONS_ACTIVENEWWINDOW      32854
#define ID_OPTIONS_MYIESTARTUP_OPENBLANKPAGE 32855
#define ID_OPTIONS_MYIESTARTUP_RESUMELASTVISITEDPAGES 32856
#define ID_OPTIONS_MYIESTARTUP_OPENFAVORITEPAGES 32857
#define ID_RFAV_START                   32858
#define ID_RFAV_COPY                    32859
#define ID_RFAV_DEL                     32860
#define ID_RFAV_PROPERTY                32861
#define ID_RFAV_OPENALL                 32862
#define ID_RFAV_DEL_FOLDER              32863
#define ID_RTAB_CLOSE_OTHER             32864
#define ID_RTAB_ADDFAV                  32865
#define ID_VIEW_LINKS                   32866
#define ID_RFAV_START_FOLDER            32867
#define ID_LINK_POPUP                   32868
#define ID_OPTION_MULTI_TAB             32869
#define ID_MENU_BAR                     32869
#define ID_HELP_MAIL                    32870
#define ID_SYSMENU_BAR                  32870
#define ID_HELP_FORUM                   32871
#define ID_TOOLS_OPENALLLINKS           32872
#define ID_FILE_NEW_CLIP                32873
#define ID_FILE_CLOSE_KEEPCUR           32874
#define ID_HELP_HOMEPAGE                32875
#define ID_VIEW_REFRESHALL              32876
#define ID_OPTION_ALWAYS_NEW            32877
#define ID_OPTIONS_NEWTAB               32878
#define ID_VIEW_STOP_ALL                32879
#define ID_TOOLS_IP                     32881
#define ID_WINDOW_RESTOR                32882
#define ID_MENUITEM32883                32883
#define ID_WINDOW_MIN                   32884
#define ID_VIEW_MENUBAR                 32886
#define ID_TOOLS_SETBACKGROUNDPIC_NONE  32888
#define ID_RFAV_OPEN_NEW                32890
#define ID_FILE_NEWMYIE                 32891
#define ID_FILE_OPENF                   32892
#define ID_VIEW_TOOLBARTEXTLABEL        32893
#define IDS_PASSWORD_ERROR              32893
#define ID_FAVORITES_BEST               32894
#define ID_SP_INVALID                   32895
#define ID_SP_SLOWER                    32896
#define ID_SP_SLOW                      32897
#define ID_SP_NOR                       32898
#define ID_SP_FAST                      32899
#define ID_SP_FASTER                    32900
#define ID_TOOLS_OPENSTART              32901
#define ID_OPTION_AUTOTAB               32902
#define ID_SHORTCUT_ALIAS               32903
#define ID_SHORTCUT_MANALIAS            32904
#define ID_SHORTCUT_USE_SC              32905
#define ID_SHORTCUT_SC                  32906
#define ID_SHORTCUT_MFL                 32907
#define ID_RFAV_MOST_FAV                32908
#define ID_RFAV_ALIAS                   32909
#define ID_RFAVFOLDER_OPENMOSTFAVORITES 32910
#define ID_F_2                          32913
#define ID_F_3                          32914
#define ID_F_4                          32915
#define ID_F_5                          32916
#define ID_F_6                          32917
#define ID_F_7                          32918
#define ID_F_8                          32919
#define ID_F_9                          32920
#define ID_F_10                         32921
#define ID_F_11                         32922
#define ID_F_12                         32923
#define ID_RFAV_ADDSHORTCUT             32924
#define ID_VIEW_TOOLBARS_CUSTOMIZE      32925
#define ID_OPTIONS_MYIEGOHOME           32927
#define ID_OPTIONS_MYIESTARTUP_OPENMOSTFAVORITEPAGES 32928
#define ID_SHORTCUTS_USE3721            32929
#define ID_RTAB_STICKNAME               32930
#define ID_OPTION_SEQ_DEFAULT           32931
#define ID_OPTION_SEQ_NEXT              32932
#define ID_OPTION_SEQ_PRE               32933
#define ID_TAB_PRE                      32934
#define ID_TAB_NEXT                     32935
#define ID_OPTIONS_URLINSTATUS          32936
#define ID_C_1                          32939
#define ID_C_2                          32940
#define ID_C_3                          32941
#define ID_C_4                          32942
#define ID_C_5                          32943
#define ID_C_6                          32944
#define ID_C_7                          32945
#define ID_C_8                          32946
#define ID_C_9                          32947
#define ID_C_0                          32948
#define ID_RTAB_REFRESH                 32950
#define ID_RTAB_STOP                    32951
#define ID_FILE_PRINTPREVIEW            32952
#define ID_VIEW_FAVS                    32953
#define ID_RFAV_MOST_FOLDER             32954
#define ID_RTAB_PROTECT                 32955
#define ID_RFAVFOLDER_NEW_FOLDER        32956
#define ID_RFAVFOLDER_FIND              32957
#define ID_VIEW_EX_TOOL                 32959
#define ID_EDIT_EDIT                    32960
#define ID_MENUITEM32961                32961
#define ID_FILE_STOP_OPENALL            32962
#define ID_FILE_HIDE                    32963
#define ID_VIEW_FOLDER                  32964
#define ID_OPTIONS_OPENLINKINNEWWINDOW  32965
#define ID_OPTIONS_BROWSEMODES_DEFAULT  32966
#define ID_OPTIONS_BROWSEMODES_NEWS     32967
#define ID_OPTIONS_BROWSEMODES_STANDARD 32968
#define ID_VIEW_EXPLOREBAR_RESOURCE     32969
#define ID_TOOLS_AUTOSCROLL_AUTOSCROLLINGAFTERDOWNLOADING 32970
#define ID_TOOLS_AUTOSCROLL_SLOW        32971
#define ID_TOOLS_AUTOSCROLL_MEDIUM      32972
#define ID_TOOLS_AUTOSCROLL_FAST        32973
#define ID_TOOLS_AUTOSCROLL_USEAUTOSCROLLING 32974
#define ID_EDIT_UNDOCLOSE               32975
#define IDS_UNDO_CLOSE                  32976
#define ID_ORGGROUP                     32977
#define ID_ADDTOGROUP                   32978
#define ID_OPTIONS_MYIESTARTUP_OPENSTARTUPGROUP 32979
#define ID_NEWWINDOW                    32980
#define ID_RFAVFOLDER_RESET             32981
#define ID_NEWWINDOW_FAV                32982
#define ID_NEWWINDOW_HISTORY            32984
#define ID_NEWWINDOW_FILE               32985
#define ID_FILE_SENDPAGEBYEMAIL         32986
#define ID_FILE_QUICKSAVE               32987
#define ID_FILE_SENDLINKBYEMAIL         32988
#define ID_RFAV_RENAME                  32989
#define ID_TOOLS_SETBG                  32991
#define ID_TOOLS_SELBG                  32992
#define ID_HELP_VISITDEVELOPERSFORUM    32993
#define ID_HISFOLDER_DELETE             32994
#define ID_HISURL_DELETE                32995
#define ID_HISURL_ADDTOFAVORITES        32996
#define ID_HISURL_PROPERTIES            32997
#define ID_OPTIONS_EXPORTPROXYLIST      32998
#define ID_OPTIONS_IMPORTPROXYLIST      32999
#define ID_TOOLS_MEM                    33000
#define ID_VIEW_ENCODING_JANESEEUC      33001
#define ID_VIEW_ENCODING_JANESEAUTO     33002
#define ID_TOOLS_AUTOREF                33004
#define ID_TOOLS_REFFRE                 33005
#define ID_RTAB_AUTOREF                 33006
#define ID_RTAB_REFFRE                  33007
#define ID_VIEW_LOCK                    33008
#define ID_TOOLS_AUTOFILTER_CUR         33009
#define ID_TOOLS_ALL_BK                 33010
#define ID_TOOLS_QUICKSEARCH            33011
#define ID_TOOLS_SYNC                   33012
#define ID_SC_SAVEFORM                  33013
#define ID_SC_SAVEGENFORM               33014
#define ID_SC_FILLFORM                  33015
#define ID_TOOLS_COLLECT                33016
#define ID_OPTIONS_DOWNLOAD             33017
#define ID_TOOLS_CLEANADDR              33018
#define ID_ALL_PAGE_LINKS               33019
#define ID_TOOLS_AUTOSETBG              33020
#define ID_VIEW_ENCODING_AUTO           33021
#define ID_FILE_PROPERTY                33022
#define ID_SAVEAS_GROUP                 33023
#define ID_GROUP                        33024
#define ID_FILE_AUTOSAVE                33025
#define ID_TOOL_CLEANMYIEFORM           33026
#define ID_RTAB_AUTOSAVE                33028
#define ID_RTAB_ADDALIAS                33029
#define ID_RTAB_ADDSC                   33030
#define ID_VIEW_WIN_PRE                 33031
#define ID_VIEW_WIN_NEXT                33032
#define ID_VIEW_WIN_CLOSEALL            33033
#define ID_VIEW_WIN_MIN                 33034
#define ID_VIEW_WIN_RESTORE             33035
#define ID_VIEW_WIN_CLOSE               33036
#define ID_TOOLS_MOUSE_SCR              33037
#define ID_TOOLS_URL_FILTER             33038
#define ID_OPTIONS_MYIESTARTUP_NONE     33039
#define ID_TOOLS_BP                     33040
#define ID_VIEW_LOCKTOOLBAR             33041
#define ID_TOOLS_AUTOSCROLL_ALL         33043
#define ID_INDICATOR_PROCESS            59143
#define ID_INDICATOR_WINS               59144
#define ID_INDICATOR_BPS                59145
#define ID_INDICATOR_IP                 59145
#define ID_INDICATOR_BP                 59146
#define ID_INDICATOR_RES                59147
#define ID_INDICATOR_SECU               59148
#define ID_INDICATOR_TOOLS              59149

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        217
#define _APS_NEXT_COMMAND_VALUE         33044
#define _APS_NEXT_CONTROL_VALUE         1191
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
